### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by anitera** [kappazeta/cloudmask-fit#1]
Hi,
I've followed the instruction in readme, but meet an error. Can you please help me what could be the issue?
```
2020-08-04 09:27:20.717981: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-04 09:27:21.037574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-04 09:27:21.857441: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-08-04 09:27:22.008571: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
ERROR: CMF: Unhandled exception
Traceback (most recent call last):
  File "cm-fit.py", line 59, in main
    cmf.train()
  File "/home/rita/Documents/kappazeta/cloudmask-fit/cm_fit/cm_fit.py", line 249, in train
    self.model.fit(dataset_train, dataset_val)
  File "/home/rita/Documents/kappazeta/cloudmask-fit/cm_fit/model/model.py", line 143, in fit
    self.model.fit(
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/rita/anaconda3/envs/cm_fit/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/conv2d/Conv2D (defined at /home/rita/Documents/kappazeta/cloudmask-fit/cm_fit/model/model.py:143) ]] [Op:__inference_train_function_2085]

Function call stack:
train_function
```
**Steps to reproduce:**
```
python3 cm-fit.py -c config/config_example.json
```

**Comment by indrek-sunter** [comment]
Can you check the version of the conda tensorflow packages:
`conda list | grep tensorflow`

Also, could you check the version of the graphics card drivers:
`nvidia-smi`

For reference, I currently have the following:
```
$ conda list | grep tensorflow
tensorflow                2.2.0           gpu_py38hb782248_0  
tensorflow-base           2.2.0           gpu_py38h83e3d50_0  
tensorflow-estimator      2.2.0              pyh95af2a2_0    conda-forge
tensorflow-gpu            2.2.0                h0d30ee6_0  

$ nvidia-smi
Tue Aug  4 10:41:57 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 00000000:02:00.0  On |                  N/A |
| 43%   45C    P0     2W /  39W |    471MiB /  4040MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1468      G   /usr/lib/xorg/Xorg                           338MiB |
|    0      4037      G   ...equest-channel-token=840432356298562790    74MiB |
|    0      4191      G   ...quest-channel-token=5813948831895288073    54MiB |
+-----------------------------------------------------------------------------+
```

**Comment by anitera** [comment]
Tensorflow info:
```conda list | grep tensorflow
tensorflow                2.2.0           gpu_py38hb782248_0  
tensorflow-base           2.2.0           gpu_py38h83e3d50_0  
tensorflow-estimator      2.2.0              pyh95af2a2_0    conda-forge
tensorflow-gpu            2.2.0                h0d30ee6_0 
```

GPU info:
```nvidia-smi
Tue Aug  4 10:46:03 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8     6W /  N/A |    736MiB /  7982MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1195      G   /usr/lib/xorg/Xorg                            28MiB |
|    0      1408      G   /usr/bin/gnome-shell                          49MiB |
|    0      3508      G   /usr/lib/xorg/Xorg                           302MiB |
|    0      3680      G   /usr/bin/gnome-shell                         231MiB |
|    0      4121      G   ...uest-channel-token=12534817977810330790    60MiB |
|    0      5734      G   ...equest-channel-token=643126356479947187    35MiB |
|    0      7745      G   ...pycharm-community-2020.1.1/jbr/bin/java    22MiB |
+-----------------------------------------------------------------------------+
```

**Comment by indrek-sunter** [comment]
Updated my drivers to 440 but failed to reproduce the issue.

```
Tue Aug  4 11:16:01 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 00000000:02:00.0  On |                  N/A |
| 47%   60C    P0    13W /  39W |   3987MiB /  4040MiB |     60%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1579      G   /usr/lib/xorg/Xorg                           232MiB |
|    0      3347      G   ...quest-channel-token=1138356858097519945    42MiB |
|    0      3471      G   ...uest-channel-token=14006033701077003257    56MiB |
|    0      5013      C   ...zeta/miniconda3/envs/cm_fit/bin/python3  3639MiB |
+-----------------------------------------------------------------------------+


/home/kappazeta/miniconda3/envs/cm_fit/bin/python3 /home/kappazeta/Documents/projects/cloudmask-fit/cm-fit.py
INFO: CMF: CloudMask Fit started..
INFO: CMF: Dataset split as follows:
 Total: 258706
 Train: 181093 (70.00%)
 Validation: 51741 (20.00%)
 Test: 25870 (10.00%)
2020-08-04 11:00:16.089361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-04 11:00:16.098885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: Quadro K2200 computeCapability: 5.0
coreClock: 1.124GHz coreCount: 5 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 74.65GiB/s
2020-08-04 11:00:16.099061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-04 11:00:16.100174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-04 11:00:16.101384: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-04 11:00:16.101568: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-04 11:00:16.102680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-04 11:00:16.103374: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-04 11:00:16.106256: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-04 11:00:16.107034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-04 11:00:16.107257: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-08-04 11:00:16.130696: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3491850000 Hz
2020-08-04 11:00:16.131384: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558572cc6c20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-04 11:00:16.131402: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-04 11:00:16.131878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: Quadro K2200 computeCapability: 5.0
coreClock: 1.124GHz coreCount: 5 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 74.65GiB/s
2020-08-04 11:00:16.131916: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-04 11:00:16.131933: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-04 11:00:16.131949: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-04 11:00:16.131964: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-04 11:00:16.131979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-04 11:00:16.131994: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-04 11:00:16.132008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-04 11:00:16.132750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-04 11:00:16.132786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-04 11:00:16.161955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-04 11:00:16.161975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-04 11:00:16.161981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-08-04 11:00:16.163052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3362 MB memory) -> physical GPU (device: 0, name: Quadro K2200, pci bus id: 0000:02:00.0, compute capability: 5.0)
2020-08-04 11:00:16.166287: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55857398b3f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-04 11:00:16.166324: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro K2200, Compute Capability 5.0
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input (InputLayer)              [(None, 9, 9, 13)]   0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 9, 9, 32)     3776        input[0][0]                      
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 9, 9, 32)     9248        conv2d[0][0]                     
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 3, 3, 32)     0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 3, 3, 64)     18496       max_pooling2d[0][0]              
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 3, 3, 64)     36928       conv2d_2[0][0]                   
__________________________________________________________________________________________________
dropout (Dropout)               (None, 3, 3, 64)     0           conv2d_3[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 1, 1, 64)     0           dropout[0][0]                    
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 1, 1, 128)    73856       max_pooling2d_1[0][0]            
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 1, 1, 128)    147584      conv2d_4[0][0]                   
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 1, 1, 128)    0           conv2d_5[0][0]                   
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 3, 3, 128)    0           dropout_1[0][0]                  
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 3, 3, 64)     32832       up_sampling2d[0][0]              
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 3, 3, 128)    0           dropout[0][0]                    
                                                                 conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 3, 3, 64)     73792       concatenate[0][0]                
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 3, 3, 64)     36928       conv2d_7[0][0]                   
__________________________________________________________________________________________________
up_sampling2d_1 (UpSampling2D)  (None, 9, 9, 64)     0           conv2d_8[0][0]                   
__________________________________________________________________________________________________
conv2d_9 (Conv2D)               (None, 9, 9, 32)     8224        up_sampling2d_1[0][0]            
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 9, 9, 64)     0           conv2d_1[0][0]                   
                                                                 conv2d_9[0][0]                   
__________________________________________________________________________________________________
conv2d_10 (Conv2D)              (None, 9, 9, 32)     18464       concatenate_1[0][0]              
__________________________________________________________________________________________________
conv2d_11 (Conv2D)              (None, 9, 9, 32)     9248        conv2d_10[0][0]                  
__________________________________________________________________________________________________
conv2d_12 (Conv2D)              (None, 9, 9, 16)     4624        conv2d_11[0][0]                  
__________________________________________________________________________________________________
conv2d_13 (Conv2D)              (None, 9, 9, 5)      85          conv2d_12[0][0]                  
__________________________________________________________________________________________________
flatten (Flatten)               (None, 405)          0           conv2d_13[0][0]                  
__________________________________________________________________________________________________
output (Dense)                  (None, 5)            2030        flatten[0][0]                    
==================================================================================================
Total params: 476,115
Trainable params: 476,115
Non-trainable params: 0
__________________________________________________________________________________________________
Epoch 1/300
2020-08-04 11:04:44.893212: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-04 11:04:45.361150: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-04 11:04:46.646679: W tensorflow/stream_executor/gpu/asm_compiler.cc:81] Running ptxas --version returned 256
2020-08-04 11:04:46.684177: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
5660/5659 [==============================] - 92s 16ms/step - loss: 0.3067 - accuracy: 0.8920 - val_loss: 0.2180 - val_accuracy: 0.9192 - lr: 1.0000e-04
Epoch 2/300
```

Since I ended up with 440.100 instead of 440.33.01, I wonder if it could be an issue with the driver version 440.33.01.

Alternatively, you could try `tensorflow` or `tensorflow-mkl` instead of `tensorflow-gpu` in `environment.yml` (https://github.com/kappazeta/cloudmask-fit/blob/master/environment.yml). Though, I think that there would be a noticeable performance hit without the Tensorflow GPU.

**Comment by anitera** [comment]
I downgraded drivers to the same configs you have previously:
```
nvidia-smi
Tue Aug  4 11:44:52 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8     9W /  N/A |    360MiB /  7982MiB |     30%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1240      G   /usr/lib/xorg/Xorg                            28MiB |
|    0      1583      G   /usr/bin/gnome-shell                          50MiB |
|    0      2327      G   /usr/lib/xorg/Xorg                           139MiB |
|    0      2499      G   /usr/bin/gnome-shell                          79MiB |
|    0      2899      G   ...uest-channel-token=15475629472150779951    60MiB |
+-----------------------------------------------------------------------------+
```
But still exactly same error. My guess that it is not gpu-drivers issue, maybe I'm missing some packages. I'll try to run on CPU next.

**Comment by anitera** [comment]
The issue is solved by upgrading **tenworflow-gpu** to **2.3.0** version with ```pip install tensorflow-gpu==2.3.0```. Now, the output of command conda list | grep tensorflow is the following:

```
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorflow-gpu            2.3.0                    pypi_0    pypi
```

**Comment by indrek-sunter** [comment]
For reference, `environment.yml` now installs **tensorflow-gpu** version **2.3.0** or newer via pip (in conda, the latest version is 2.2.0).
https://github.com/kappazeta/cloudmask-fit/commit/89d6fbb11d00719183d75c0456a039001ea2c47a
